version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: pixelart
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: flask run --host=0.0.0.0
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis

  celery:
    build: ./backend
    command: celery -A celery_worker worker --loglevel=info
    depends_on:
      - backend
      - redis
